"""
Commit suggestion model for write mode.
"""

from pydantic import BaseModel, Field


class ChangeSummary(BaseModel):
    """Summary of detected changes in the diff."""

    files_changed: int = Field(description="Number of files changed")
    insertions: int = Field(description="Number of lines added")
    deletions: int = Field(description="Number of lines deleted")
    change_descriptions: list[str] = Field(
        description="List of high-level descriptions of what changed"
    )


class CommitSuggestion(BaseModel):
    """A suggested commit message generated by the AI."""

    title: str = Field(
        description="The commit title/subject line (first line)"
    )
    body: str | None = Field(
        default=None,
        description="The commit body with detailed bullet points"
    )
    commit_type: str = Field(
        description="The type of commit (feat, fix, refactor, docs, test, chore, etc.)"
    )
    scope: str | None = Field(
        default=None,
        description="The scope/area of the codebase affected"
    )

    @property
    def full_message(self) -> str:
        """Get the complete commit message."""
        if self.body:
            return f"{self.title}\n\n{self.body}"
        return self.title

    @property
    def conventional_title(self) -> str:
        """Get the title in conventional commit format."""
        if self.scope:
            return f"{self.commit_type}({self.scope}): {self._strip_prefix(self.title)}"
        return f"{self.commit_type}: {self._strip_prefix(self.title)}"

    def _strip_prefix(self, title: str) -> str:
        """Strip any existing conventional commit prefix from the title."""
        # Remove patterns like "feat:", "fix(scope):", etc.
        import re
        pattern = r'^[a-z]+(\([^)]+\))?\s*:\s*'
        return re.sub(pattern, '', title)

